# config/smartfallmm/distill.yaml
teacher_model: models.mm_transformer.MMTransformer
model: models.transformer_optimized.TransModel
dataset: smartfallmm

subjects: [32, 39, 30, 31, 34, 35, 37, 43, 44, 45, 36, 29]

teacher_args:
  mocap_frames: 128
  acc_frames: 128
  num_joints: 32
  in_chans: 3
  num_patch: 2
  acc_coords: 3
  spatial_embed: 32
  sdepth: 2
  adepth: 2
  tdepth: 2
  num_heads: 2
  num_classes: 1

model_args:
  num_classes: 1
  num_heads: 4
  embed_dim: 32
  num_layers: 2
  dropout: 0.5
  activation: 'relu'
  acc_frames: 128
  acc_coords: 3

dataset_args: 
  mode: 'sliding_window'
  max_length: 128
  task: 'fd'
  modalities: ['skeleton', 'accelerometer']
  age_group: ['young']
  sensors: ['watch']

distill_args:
  T: 2.0
  alpha: 0.7
  fuse: false

batch_size: 64
test_batch_size: 64
val_batch_size: 64
num_epoch: 100

feeder: utils.dataset_tf.UTD_MM_TF

seed: 2
optimizer: adamw
base_lr: 1e-3
weight_decay: 1e-4

# Point to your teacher model weights
teacher_weight: ../exps/smartfall_fall_wokd/teacher/skeleton_with_experimental_90.57/spTransformer
