# config/smartfallmm/teacher.yaml
model: models.mm_transformer.MMTransformer
dataset: smartfallmm

# Subjects configuration
# Note: Subjects 1-28 (older participants with ADL data only) will be automatically 
# added to fixed training set if they have valid accelerometer+skeleton data
subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44, 45, 36, 29]  # Younger subjects only

# Cross-validation setup
# Older subjects (1-28) will be automatically added to train_subjects_fixed
train_subjects_fixed: [45, 36, 29]  # Fixed younger subjects for training
val_subjects_fixed: [38, 46]        # Validation subjects (younger only)
# Test eligible: remaining younger subjects not in fixed sets

# Whether to include older subjects (1-28) in training
include_older_subjects: true  # Set to false to use only younger subjects

model_args:
  acc_frames: 64
  mocap_frames: 64
  num_joints: 32
  in_chans: 3
  spatial_embed: 32
  tdepth: 2
  num_heads: 2
  mlp_ratio: 2.0
  drop_rate: 0.2
  attn_drop_rate: 0.2
  drop_path_rate: 0.2
  num_classes: 1

dataset_args:
  mode: 'selective_window'
  max_length: 64
  task: 'fd'
  modalities: ['skeleton', 'accelerometer']
  age_group: ['young', 'old']  # Include both age groups for training
  sensors: ['watch']
  use_dtw: true
  verbose: true
  fall_height: 1.4
  fall_distance: 50
  non_fall_height: 1.2
  non_fall_distance: 100

batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 80
feeder: utils.dataset_tf.UTD_MM_TF
optimizer: adamw
base_lr: 0.0001
weight_decay: 0.0004
seed: 2
