# config/smartfallmm/distill.yaml
model: models.transformer_optimized.TransModel
teacher_model: models.mm_transformer.MMTransformer
dataset: smartfallmm

# Subjects for fall detection
subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44, 45, 36, 29]

model_args:
  acc_frames: 128
  num_classes: 1
  num_heads: 4
  acc_coords: 3
  embed_dim: 32
  num_layers: 2
  dropout: 0.5

teacher_args:
  mocap_frames: 128
  acc_frames: 128
  num_joints: 32
  in_chans: 3
  num_patch: 4
  acc_coords: 3
  spatial_embed: 16
  sdepth: 4
  adepth: 4
  tdepth: 2
  num_heads: 2
  mlp_ratio: 2
  qkv_bias: true
  drop_rate: 0.2
  attn_drop_rate: 0.2
  drop_path_rate: 0.2
  num_classes: 1

# Distillation parameters
temperature: 4.5
alpha: 0.6

dataset_args: 
  mode: 'sliding_window'
  max_length: 128
  task: 'fd'
  modalities: ['accelerometer','skeleton']  # Student only needs accelerometer
  age_group: ['young']
  sensors: ['watch']
  use_dtw: true # No need for DTW with only accelerometer

feeder: feeder.make_dataset_tf.UTD_MM_TF
batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 80
optimizer: adamw
base_lr: 0.001
weight_decay: 0.0004

# Path to teacher model weights (will be set by distill.sh)
teacher_weight: "../experiments/latest_teacher/models/teacher_model.weights.h5"
