model: src.models.transformer_optimized.TransModel
dataset: smartfallmm

# Subjects for fall detection
subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44, 45, 36, 29]

model_args:
  acc_frames: 64 
  num_classes: 1
  num_heads: 4
  acc_coords: 3  # Original accelerometer channels (SMV is added internally)
  embed_dim: 32  # Match PyTorch implementation
  num_layers: 2
  dropout: 0.5
  activation: 'relu'

dataset_args: 
  mode: 'sliding_window'
  max_length: 64
  task: 'fd'
  modalities: ['accelerometer', 'skeleton']  # Keep both for DTW alignment
  age_group: ['young']
  sensors: ['watch']
  use_dtw: true
feeder: utils.dataset_tf.UTD_MM_TF
batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 80

optimizer: adamw
base_lr: 0.0005
weight_decay: 0.0004

phase: 'train'
seed: 2
print_log: True
