# src/config/smartfallmm/student.yaml
model: models.transformer_optimized.TransModel
dataset: smartfallmm

# Subjects configuration
# Note: Subjects 1-28 (older participants with ADL data only) will be automatically 
# added to fixed training set if they have valid accelerometer+skeleton data
subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44, 45, 36, 29]  # Younger subjects only

# Cross-validation setup
# Older subjects (1-28) will be automatically added to train_subjects_fixed
train_subjects_fixed: [45, 36, 29]  # Fixed younger subjects for training
val_subjects_fixed: [38, 46]        # Validation subjects (younger only)
# Test eligible: remaining younger subjects not in fixed sets

# Whether to include older subjects (1-28) in training
include_older_subjects: false # Set to false to use only younger subjects

model_args:
  acc_frames: 128
  num_classes: 1
  num_heads: 4
  acc_coords: 3
  embed_dim: 32
  num_layers: 2
  dropout: 0.5
  activation: 'relu'
  norm_first: true

dataset_args:
  mode: 'selective_window'
  max_length: 128
  task: 'fd'
  modalities: ['accelerometer', 'skeleton']
  age_group: ['young', 'old']  # Include both age groups for training
  sensors: ['watch']
  use_dtw: true
  verbose: true
  fall_height: 1.4
  fall_distance: 50
  non_fall_height: 1.2
  non_fall_distance: 100

feeder: utils.dataset_tf.UTD_MM_TF
batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 80
optimizer: adamw
base_lr: 0.0005
weight_decay: 0.0004
use_smv: false
seed: 2
print_log: true
