# config/smartfallmm/student.yaml
model: models.transformer_optimized.TransModel
dataset: smartfallmm

# Subjects for fall detection
subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44, 45, 36, 29]

model_args:
  acc_frames: 64 
  num_classes: 1
  num_heads: 4
  acc_coords: 3
  embed_dim: 32
  num_layers: 2
  dropout: 0.5
  activation: 'relu'
  norm_first: true

dataset_args: 
  mode: 'selective_window'  # Changed from sliding_window to match PyTorch
  max_length: 64
  task: 'fd'
  modalities: ['accelerometer', 'skeleton']
  age_group: ['young']
  sensors: ['watch']
  use_dtw: true
  verbose: true
  # Peak detection parameters from PyTorch
  fall_height: 1.4
  fall_distance: 50
  non_fall_height: 1.2
  non_fall_distance: 100

# Data loading
feeder: utils.dataset_tf.UTD_MM_TF
batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 80
use_smv: false

# Optimization
optimizer: adamw
base_lr: 0.001
weight_decay: 0.0004

# Processing
num_worker: 4
seed: 2
print_log: true

# Cross-validation definition
train_subjects_fixed: [45, 36, 29]
val_subjects_fixed: [38, 46]
test_eligible_subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44]
