# config/smartfallmm/teacher.yaml
model: models.mm_transformer.MMTransformer
dataset: smartfallmm

# Subjects for fall detection
subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44, 45, 36, 29]

model_args:
  acc_frames: 128
  num_joints: 32
  num_classes: 1
  spatial_embed: 16
  adepth: 2
  sdepth: 2
  num_heads: 2
  mocap_frames: 128
  num_patch: 4
  in_chans: 3
  acc_coords: 3
  tdepth: 2
  mlp_ratio: 2
  qkv_bias: true
  drop_rate: 0.2
  attn_drop_rate: 0.2
  drop_path_rate: 0.2

dataset_args: 
  mode: 'selective_window'  # Changed from sliding_window
  max_length: 128
  task: 'fd'
  modalities: ['skeleton', 'accelerometer']
  age_group: ['young']
  sensors: ['watch']
  use_dtw: true
  verbose: true
  # Peak detection parameters  
  fall_height: 1.4
  fall_distance: 50
  non_fall_height: 1.2
  non_fall_distance: 100

batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 80

# Data feeder
feeder: utils.dataset_tf.UTD_MM_TF

# Optimizer settings
optimizer: adamw
base_lr: 0.001
weight_decay: 0.0004

# Random seed
seed: 2

# Cross-validation configuration
train_subjects_fixed: [45, 36, 29]
val_subjects_fixed: [38, 46]
test_eligible_subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44]
