# teacher.yaml - Configuration for training the teacher model
model: models.mm_transformer.MMTransformer
dataset: smartfallmm

# Subjects for fall detection
subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44, 45, 36, 29]

model_args:
  mocap_frames: 128
  acc_frames: 128
  num_joints: 32
  in_chans: 3
  num_patch: 2
  acc_coords: 4
  spatial_embed: 96
  sdepth: 2
  adepth: 2
  tdepth: 2
  num_heads: 2
  num_classes: 1
  mlp_ratio: 2

dataset_args:
  mode: 'sliding_window'
  max_length: 128
  task: 'fd'
  modalities: ['skeleton', 'accelerometer']
  age_group: ['young']
  sensors: ['watch']

batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 50

feeder: utils.dataset_tf.UTD_MM_TF
optimizer: adamw
base_lr: 0.001
weight_decay: 0.0004
