# config/smartfallmm/teacher.yaml
model: models.mm_transformer.MMTransformer
dataset: smartfallmm

subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44, 45, 36, 29]

model_args:
  mocap_frames: 128
  acc_frames: 128
  num_joints: 32
  in_chans: 3
  num_patch: 4
  acc_coords: 3
  spatial_embed: 16
  sdepth: 4
  adepth: 4
  tdepth: 2
  num_heads: 2
  mlp_ratio: 2
  qkv_bias: true
  op_type: 'pool'
  embed_type: 'lin'
  drop_rate: 0.2
  attn_drop_rate: 0.2
  drop_path_rate: 0.2
  num_classes: 1

dataset_args: 
  mode: 'sliding_window'
  max_length: 128
  task: 'fd'
  modalities: ['accelerometer', 'skeleton']
  age_group: ['young']
  sensors: ['watch']
  use_dtw: true

feeder: feeder.make_dataset_tf.UTD_MM_TF
batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 80
optimizer: adamw
base_lr: 0.001
weight_decay: 0.0004
