# Unified configuration for teacher training and student distillation

# General settings
dataset: smartfallmm
subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44, 45, 36, 29]
phase: 'train'
seed: 2
print_log: True

# Dataset arguments (consistent across teacher and student)
dataset_args:
  mode: 'sliding_window'
  max_length: 64
  task: 'fd'
  modalities: ['accelerometer', 'skeleton']
  age_group: ['young']
  sensors: ['watch']
  use_dtw: true

# Model arguments for teacher
teacher_model: models.mm_transformer.MMTransformerTF
teacher_args:
  num_classes: 1
  num_joints: 32
  embed_dim: 32
  num_heads: 4
  num_layers: 2
  window_size: 64
  acc_coords: 4  # Includes SMV

# Model arguments for student
model: models.mm_transformer.MMTransformerTF
model_args:
  num_classes: 1
  num_joints: 32
  embed_dim: 32
  num_heads: 4
  num_layers: 2
  window_size: 64
  acc_coords: 4  # Includes SMV

# Training hyperparameters for teacher
teacher_batch_size: 16
teacher_num_epoch: 60
teacher_optimizer: adamw
teacher_base_lr: 0.001
teacher_weight_decay: 0.0004

# Training hyperparameters for student
batch_size: 16
num_epoch: 60
optimizer: adamw
base_lr: 0.001
weight_decay: 0.0004

# Distillation parameters
temperature: 4.5
alpha: 0.6

# Experiment settings
work_dir: exps/test
model_saved_name: ttfstudent
teacher_weight: "experiments/teacher/teacher_weights.h5"
feeder: utils.dataset_tf.UTD_MM_TF
data_path: './data'
shuffle_buffer: 1000
