subjects : [29,31, 32, 34, 35, 36, 37]

student_path: exp/smartfallmm/test/models/transformer
teacher_path: exp/smartfallmm/test/models/convtransformer

processing_args: 
  data_dir : 'datasets/smartfallmm/student_participants'
  skl_window_size : 128
  num_windows : 10
  acc_window_size : 128
  num_joints : 32
  num_channels : 3
  
student_args: 
  length : 128 
  acc_dim : 3
  embed_dim : 128
  num_heads : 4
  depth : 4
  num_patch : 4
  drop : 0.2
  attn_drop : 0.4
  mlp_ratio : 4.
  num_classes : 2

teacher_args: 
  mocap_frames: 128
  acc_frames:  128 
  num_joints:  32
  in_chans:  3
  acc_cords:  3 
  embed_size:  128
  num_heads: 8 
  depth:  4
  drop_rate:  0.2
  num_patch:  4 
  attn_drop_rate:  0.2 
  drop_path_rate:  0.2
  mlp_ratio:  2
  num_classes:  2

epochs: 30